
name : Git Pull Upstream
on :
  schedule :
    - cron : '0 0 * * 0,1'
jobs:
  git-pull :
    runs-on : ubuntu-latest
    steps:
    - name : checkout code
      uses : actions/checkout@v2
      with:
        repository: https://github.com/jnear/cs3110-data-privacy.git
        ref : main
    - name : Git Pull
      run : git pull
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
